export const dynamic = "force-static";

const nonEmptyString = { type: "string", minLength: 1 } as const;
const nullableString = { type: ["string", "null"] } as const;
const stringArray = { type: "array", items: { type: "string" } } as const;

const storySpecimen = {
  type: "object",
  additionalProperties: false,
  required: ["availability", "evidenceStatus", "sourcePointer", "unavailableReason", "url"],
  properties: {
    availability: nonEmptyString,
    evidenceStatus: nonEmptyString,
    sourcePointer: { type: ["object", "null"] },
    unavailableReason: nullableString,
    url: { type: "string", format: "uri" },
  },
} as const;

export function GET() {
  return Response.json({
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://mergora.vercel.app/m/v1/schemas/item-doc.schema.json",
    title: "Mergora machine item documentation",
    type: "object",
    additionalProperties: false,
    required: [
      "schemaVersion",
      "kind",
      "id",
      "displayName",
      "family",
      "layer",
      "summary",
      "normativeBehavior",
      "canonicalUrl",
      "immutableVersionUrl",
      "contentVersion",
      "sourceCommit",
      "publicationStatus",
      "sourceAvailable",
      "implementationStatus",
      "targetMaturity",
      "publishedMaturity",
      "trust",
      "riskClass",
      "requiredStateGroups",
      "requiredEvidenceFamilies",
      "anatomy",
      "stateApplicability",
      "accessibilityContract",
      "api",
      "implementation",
      "sourceAndEvidence",
      "specimens",
      "guidance",
      "related",
      "reviewNotice",
      "generatedDigest",
    ],
    properties: {
      schemaVersion: { const: 1 },
      kind: { enum: ["item-doc", "kit-doc"] },
      id: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
      displayName: nonEmptyString,
      family: nonEmptyString,
      layer: { enum: ["foundation", "component", "system", "kit"] },
      summary: nonEmptyString,
      normativeBehavior: nonEmptyString,
      canonicalUrl: { type: "string", format: "uri" },
      immutableVersionUrl: nullableString,
      contentVersion: nonEmptyString,
      sourceCommit: nonEmptyString,
      publicationStatus: { const: "blocked-unreleased" },
      sourceAvailable: { type: "boolean" },
      implementationStatus: nonEmptyString,
      targetMaturity: nonEmptyString,
      publishedMaturity: nullableString,
      trust: nonEmptyString,
      riskClass: { type: "integer", minimum: 1 },
      requiredStateGroups: stringArray,
      requiredEvidenceFamilies: stringArray,
      anatomy: {
        type: "object",
        additionalProperties: false,
        required: [
          "status",
          "sourceKind",
          "sourcePath",
          "document",
          "evidenceStatus",
          "missingEvidenceLabel",
        ],
        properties: {
          status: nonEmptyString,
          sourceKind: nonEmptyString,
          sourcePath: nullableString,
          document: true,
          evidenceStatus: nonEmptyString,
          missingEvidenceLabel: nonEmptyString,
        },
      },
      stateApplicability: {
        type: "object",
        additionalProperties: false,
        required: [
          "status",
          "sourcePath",
          "reason",
          "states",
          "evidenceStatus",
          "missingEvidenceLabel",
        ],
        properties: {
          status: nonEmptyString,
          sourcePath: nullableString,
          reason: nullableString,
          states: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: [
                "id",
                "applicability",
                "rationale",
                "availability",
                "evidenceStatus",
                "sourcePointer",
                "unavailableReason",
                "url",
              ],
              properties: {
                id: nonEmptyString,
                applicability: nonEmptyString,
                rationale: nullableString,
                availability: nonEmptyString,
                evidenceStatus: nonEmptyString,
                sourcePointer: { type: ["object", "null"] },
                unavailableReason: nullableString,
                url: { type: ["string", "null"] },
              },
            },
          },
          evidenceStatus: nonEmptyString,
          missingEvidenceLabel: nonEmptyString,
        },
      },
      accessibilityContract: {
        type: "object",
        additionalProperties: false,
        required: [
          "status",
          "sourceStatus",
          "sourcePath",
          "contractVersion",
          "claim",
          "reason",
          "semantics",
          "keyboard",
          "preferences",
          "responsive",
          "evidenceRequirements",
          "recordedEvidence",
          "evidenceStatus",
          "missingEvidenceLabel",
        ],
        properties: {
          status: nonEmptyString,
          sourceStatus: nonEmptyString,
          sourcePath: nullableString,
          contractVersion: nullableString,
          claim: nullableString,
          reason: nullableString,
          semantics: stringArray,
          keyboard: {
            type: "object",
            additionalProperties: false,
            required: ["interaction", "semanticStatements"],
            properties: {
              interaction: { type: ["object", "null"] },
              semanticStatements: stringArray,
            },
          },
          preferences: { type: ["object", "null"] },
          responsive: { type: ["object", "null"] },
          evidenceRequirements: {
            type: "object",
            additionalProperties: false,
            required: ["automated", "manual"],
            properties: { automated: stringArray, manual: stringArray },
          },
          recordedEvidence: { type: "array" },
          evidenceStatus: nonEmptyString,
          missingEvidenceLabel: nonEmptyString,
        },
      },
      api: { type: ["object", "null"] },
      implementation: { type: "object" },
      sourceAndEvidence: {
        type: "object",
        additionalProperties: false,
        required: ["source", "contract", "evidence"],
        properties: {
          source: {
            type: "object",
            additionalProperties: false,
            required: ["available", "implementationStatus", "canonicalPath", "canonicalUrl"],
            properties: {
              available: { type: "boolean" },
              implementationStatus: nonEmptyString,
              canonicalPath: nonEmptyString,
              canonicalUrl: { type: "string", format: "uri" },
            },
          },
          contract: {
            type: "object",
            additionalProperties: false,
            required: ["status", "sourceStatus", "sourcePath", "sourceUrl"],
            properties: {
              status: nonEmptyString,
              sourceStatus: nonEmptyString,
              sourcePath: nullableString,
              sourceUrl: nullableString,
            },
          },
          evidence: {
            type: "object",
            additionalProperties: false,
            required: [
              "releaseStatus",
              "accessibility",
              "interaction",
              "parity",
              "maturity",
              "missingEvidenceLabel",
            ],
            properties: {
              releaseStatus: { const: "incomplete" },
              accessibility: { type: "object" },
              interaction: { type: "object" },
              parity: { type: "object" },
              maturity: { type: "object" },
              missingEvidenceLabel: nonEmptyString,
            },
          },
        },
      },
      specimens: {
        type: "object",
        additionalProperties: false,
        required: ["stateLab", "basic", "recommended", "states"],
        properties: {
          stateLab: { type: "string", format: "uri" },
          basic: storySpecimen,
          recommended: storySpecimen,
          states: { type: "array" },
        },
      },
      guidance: {
        type: "object",
        additionalProperties: false,
        required: ["migration", "issues", "limitations"],
        properties: {
          migration: {
            type: "object",
            additionalProperties: false,
            required: ["status", "documentationUrl", "message"],
            properties: {
              status: { const: "no-public-release-history" },
              documentationUrl: { type: "string", format: "uri" },
              message: nonEmptyString,
            },
          },
          issues: {
            type: "object",
            additionalProperties: false,
            required: ["repository", "itemQuery"],
            properties: {
              repository: { type: "string", format: "uri" },
              itemQuery: { type: "string", format: "uri" },
            },
          },
          limitations: {
            type: "object",
            additionalProperties: false,
            required: ["reviewStatus", "declarations", "blockers", "missingEvidenceLabel"],
            properties: {
              reviewStatus: { const: "not-release-reviewed" },
              declarations: stringArray,
              blockers: { type: "array" },
              missingEvidenceLabel: nonEmptyString,
            },
          },
        },
      },
      related: {
        type: "object",
        additionalProperties: false,
        required: [
          "passport",
          "machineJson",
          "machineMarkdown",
          "registryItem",
          "documentationNavigation",
        ],
        properties: {
          passport: { type: "string", format: "uri" },
          machineJson: { type: "string", format: "uri" },
          machineMarkdown: { type: "string", format: "uri" },
          registryItem: { type: "string", format: "uri" },
          documentationNavigation: { type: "string", format: "uri" },
        },
      },
      reviewNotice: nonEmptyString,
      generatedDigest: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
    },
  });
}
