export const CLI_NODE_RANGE = ">=22.14.0" as const;

export { auditProject, auditProjectExitCode, type AuditProjectOptions } from "./audit.js";

export {
  auditProjectWithOfficialBrowserV1,
  type OfficialBrowserAuditOptionsV1,
  type OfficialBrowserAuditPreviewBuildV1,
  type OfficialBrowserAuditPreviewUrlV1,
  type OfficialBrowserAuditPreviewV1,
} from "./official-browser-audit.js";

export {
  applyDoctorFix,
  applyInit,
  CONFIG_SCHEMA,
  createMergoraConfig,
  MANIFEST_SCHEMA,
  mergoraConfigAliasPrefix,
  planDoctorFix,
  planInit,
  readMergoraConfig,
  validateMergoraConfig,
  type InitOptions,
  type InitPlan,
  type MergoraConfig,
} from "./configuration.js";

export {
  doctorProject,
  projectInfo,
  projectStatus,
  resolveDocumentation,
  searchRegistry,
  viewRegistryItems,
  type DoctorCheck,
  type DoctorResult,
  type DocumentationResult,
  type ItemStatus,
  type ItemView,
  type ProjectInfo,
  type ProjectStatus,
  type SearchCatalogRecord,
  type SearchOptions,
  type SearchResult,
  type StatusItem,
  type ViewOptions,
} from "./discovery.js";

export {
  inspectProject,
  type Framework,
  type PackageManager,
  type ProjectInspection,
  type ProjectInspectionOptions,
} from "./project-inspector.js";

export {
  applyProjectCreate,
  planProjectCreate,
  PROJECT_CREATE_IGNORED_OS_METADATA,
  PROJECT_CREATE_PUBLICATION_STATUS,
  PROJECT_CREATE_TEMPLATE_VERSION,
  type ProjectCreateFaultPoint,
  type ProjectCreateOptions,
  type ProjectCreatePlan,
  type ProjectCreatePreset,
  type ProjectCreateResult,
  type ProjectCreateTemplate,
} from "./project-create.js";

export {
  DOCUMENTATION_ORIGIN,
  itemDocsUrl,
  listSourceItemIds,
  loadAllSourceItems,
  loadCatalog,
  loadSourceItem,
  OFFICIAL_REGISTRY_ORIGIN,
  registryAliases,
  resolveItemAlias,
  resolveSourceDependencyClosure,
  type CatalogRecord,
  type RegistryDataOptions,
  type SourceFileRecord,
  type SourceItemRecord,
} from "./registry-data.js";

export {
  applySourceAdd,
  applyAcquiredSourceAdd,
  applySourceAdopt,
  applySourceRemove,
  deriveAcquiredDistributionSources,
  planSourceAdd,
  planAcquiredSourceAdd,
  type AcquiredSourceOperationOptions,
  type AcquiredDistributionSourceFile,
  type AcquiredDistributionSourceProjection,
  type DeriveAcquiredDistributionSourcesOptions,
  planSourceAdopt,
  planSourceRemove,
  type SourceOperationOptions,
  type SourceOperationPlan,
  type SourceOperationResult,
  type SourceRemoveOptions,
} from "./source-operations.js";

export {
  executeTransaction,
  finalizeOperationPlan,
  listIncompleteTransactions,
  planRecovery,
  planRollback,
  recoverTransaction,
  rollbackTransaction,
  TransactionInterruption,
  type ExecuteTransactionOptions,
  type OperationPlan,
  type OperationPlanDependencyChange,
  type OperationPlanFile,
  type OperationPlanItem,
  type PackageManagerInvocation,
  type PackageManagerRunner,
  type RecoveryOptions,
  type RecoveryPlan,
  type RecoveryResult,
  type RollbackOptions,
  type RollbackPlan,
  type RollbackResult,
  type TransactionFaultInjector,
  type TransactionFaultPoint,
  type TransactionMutation,
  type TransactionRegistryPayload,
  type TransactionResult,
  type TransactionState,
} from "./transaction-engine.js";

export {
  compatibleDependencyRange,
  planPackageDependencies,
  readPackageDependencies,
  type DependencyRequirement,
  type PackageDependencyChange,
  type PackageDependencyPlan,
} from "./package-editor.js";

export {
  acquireStableNpmTarballInventory,
  acquireStableVendorSnapshot,
  applyStableVendor,
  applyVendor,
  planStableVendor,
  planVendor,
  verifyVendorBundle,
  verifyVendor,
  type AcquireStableVendorSnapshotOptions,
  type StableNpmTarballFetcher,
  type StableNpmTarballFetchRequest,
  type StableNpmTarballFetchResult,
  type StableNpmTarballInventory,
  type StableNpmTarballInventoryDescriptor,
  type StableNpmTarballInventoryEntry,
  type StableVendorDocuments,
  type StableVendorPlan,
  type StableVendorResult,
  type StableVendorSnapshot,
  type VendorBundleVerificationResult,
  type VendorArtifactReference,
  type VendorItemReference,
  type VendorManifestV1,
  type VendorOptions,
  type VendorPlan,
  type VendorResult,
  type VendorVerificationResult,
  type VendorVerifyOptions,
} from "./vendor.js";

export {
  createStableAcquisitionVendorReader,
  createStableNpmTarballVendorReader,
  stableNpmTarballInternalPath,
  validateStableNpmRegistryOriginPolicies,
  validateStableNpmTarballBytes,
  validateStableNpmTarballDescriptor,
  verifyStableVendorBundle,
  verifyStableVendorBundleBytes,
  type StableAcquisitionVendorReaderOptions,
  type StableNpmRegistryOriginPolicy,
  type StableVendorNpmTarballDescriptor,
  type StableVendorNpmTarballReader,
  type StableVendorNpmTarballRequest,
  type StableVendorVerificationResult,
} from "./vendor-reader.js";

export {
  acquireImmutableArtifact,
  type AcquireImmutableArtifactOptions,
  type AcquiredImmutableArtifact,
  type AcquisitionAttempt,
  type AcquisitionDigest,
  type AcquisitionRegistryIdentity,
  type AcquisitionSource,
  type AcquisitionTransport,
  type AcquisitionTransportRequest,
  type AcquisitionTransportResponse,
  type AcquisitionTrust,
  type AcquisitionValidationContext,
  type AcquisitionValidator,
  type AcquisitionVendorReader,
  type ImmutableArtifactRequest,
} from "./acquisition.js";

export {
  assertAuthenticAcquiredNativeRegistryRelease,
  resolveNativeRegistryRelease,
  type AcquiredNativeCatalogItem,
  type AcquiredNativeFile,
  type AcquiredNativeRegistryItem,
  type AcquiredNativeRegistryRelease,
  type NativeRegistryDocumentKind,
  type NativeRegistryDocumentValidationContext,
  type NativeRegistryDocumentValidator,
  type NativeReleaseArtifactReference,
  type ResolveNativeRegistryReleaseOptions,
} from "./acquisition-resolver.js";

export {
  immutableReleaseSatisfies,
  resolveImmutableReleaseVersion,
  type ImmutableReleaseVersionPolicy,
} from "./version-resolution.js";

export {
  assertDistributionConfigurationBinding,
  assertDistributionEnrollmentAllowed,
  DISTRIBUTION_PROVENANCE_SCHEMA_VERSION,
  resolveRequestedDistributionMode,
  serializeDistributionProvenance,
  validateDistributionProvenance,
  type ConfiguredDistributionMode,
  type DistributionDependencyOwnership,
  type DistributionDigest,
  type DistributionItem,
  type DistributionPackageArtifact,
  type DistributionPatchOwnership,
  type DistributionProvenanceState,
  type DistributionReleasePin,
  type DistributionSourceFile,
  type DistributionStructuredPatch,
  type InstalledDistributionMode,
  type PackageDistributionItem,
  type SourceDistributionItem,
  type ValidatedDistributionProvenance,
} from "./distribution-provenance.js";

export {
  applyDistributionModeTransaction,
  BUILT_IN_MODE_IMPORT_ADAPTER,
  DISTRIBUTION_MODE_VALIDATOR_IDS,
  planDistributionModeTransaction,
  type ApplyDistributionModeTransactionOptions,
  type ApplyDistributionModeTransactionResult,
  type DistributionImportRewrite,
  type DistributionModeBaseMaterialization,
  type DistributionModeDependencyOperation,
  type DistributionModeFileOperation,
  type DistributionModeMigrationObservation,
  type DistributionModeMigrationOptions,
  type DistributionModeMigrationPlan,
  type DistributionModePackageIntegrityEvidence,
  type DistributionModePatchOperation,
  type DistributionModeTargetMaterialization,
  type PlanDistributionModeTransactionOptions,
  type PlanDistributionModeTransactionResult,
} from "./distribution-mode-migration.js";

export {
  applySemanticResolution,
  applyAcquiredSemanticUpdate,
  applySemanticResolveChoice,
  applySemanticUpdate,
  diffSemanticSource,
  immutableUpdateItemDigest,
  immutableUpdateRegistryIdentityDigest,
  immutableUpdateReleaseDigest,
  listSemanticResolutions,
  planSemanticResolveApply,
  planSemanticResolveChoice,
  planSemanticUpdate,
  planAcquiredSemanticUpdate,
  readImmutableUpdateRelease,
  type ImmutableUpdateFile,
  type ImmutableUpdateMove,
  type ImmutableUpdateItem,
  type ImmutableUpdateRegistry,
  type ImmutableUpdateRelease,
  type AcquiredSemanticUpdateOptions,
  type SemanticResolutionList,
  type SemanticResolveApplyOptions,
  type SemanticResolveApplyResult,
  type SemanticResolveChoice,
  type SemanticResolveChoiceOptions,
  type SemanticResolveChoicePlan,
  type SemanticSourceDiff,
  type SemanticSourceDiffFile,
  type SemanticSourceDiffOptions,
  type SemanticUpdateCommittedResult,
  type SemanticUpdateConflictResult,
  type SemanticUpdateOptions,
  type SemanticUpdateResult,
} from "./semantic-update.js";

export * from "./registry-management.js";
export * from "./theme.js";
export * from "./migrate.js";
export * from "./clean.js";

export {
  CLI_VERSION,
  CliError,
  canonicalJson,
  errorEnvelope,
  JSON_SCHEMA_VERSION,
  redactMessage,
  sha256,
  successEnvelope,
  type JsonEnvelope,
  type JsonError,
  type StableExitCode,
} from "./contracts.js";
